name: Deploy to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "deepak.mau2@gmail.com"
          git config --global user.name "github-actions"

          git clone https://user:$HF_TOKEN@huggingface.co/spaces/dpkmaurya2025/Attendance-system repo
          rsync -av --delete --exclude '.git' ./ repo/

          cd repo
          git add .
          git commit -m "Auto deploy from GitHub" || echo "No changes"
          git push